AWSTemplateFormatVersion: "2010-09-09"

Description: Cloud Formation template to configure GitHub Actions Authentication. OIDC provider, IAM role that can be supplied to GitHubAction to authenticate.

Parameters:
  GitHubOrg:
    Description: Github Organization.
    Type: String

  GitHubActionsRole:
    Description: Name of Role to be created for GitHub Actions auth
    Type: String
    Default: GitHubActionsOIDCProviderRole

  StateBucketName:
    Description: Name of S3 bucket for terraform state.
    Type: String

  StateLockTableName:
    Description: Name of Dynamo DB Table  for terraform state locking.
    Type: String

Resources:
  StatePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: StatePolicy
      Roles:
        - !Ref GitHubActionsOIDCProviderRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
              - s3:GetBucketVersioning
              - s3:GetEncryptionConfiguration
              - s3:GetBucketPolicy
              - s3:GetBucketPublicAccessBlock
              - s3:PutBucketPolicy
            Resource:
              - !Sub arn:aws:s3:::${StateBucketName}
              - !Sub arn:aws:s3:::${StateBucketName}/*
            Effect: Allow
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:DescribeTable
              - dynamodb:DeleteItem
              - dynamodb:CreateTable
            Resource: !Sub arn:aws:dynamodb:*:${AWS::AccountId}:table/${StateLockTableName}

  VpcPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: VPCPolicy
      Roles:
        - !Ref GitHubActionsOIDCProviderRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:GetCallerIdentity
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeVpcs
              - ec2:DescribeNetworkAcls
              - ec2:DescribeRouteTables
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeInternetGateways
              - ec2:DescribeSecurityGroupRules
              - logs:DescribeLogGroups
              - ec2:DescribeAddresses
              - logs:CreateLogDelivery
              - ec2:DescribeFlowLogs
              - ec2:DescribeNatGateways
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeAddressesAttribute
              - logs:ListTagsForResource
            Resource: '*'
            Effect: Allow
          - Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
              - iam:AttachRolePolicy
              - iam:PassRole
              - iam:DetachRolePolicy
              - iam:ListInstanceProfilesForRole
              - iam:DeleteRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/vpc-flow-log-role-*
            Effect: Allow
          - Action:
              - iam:CreatePolicy
              - iam:GetPolicy
              - iam:GetPolicyVersion
              - iam:ListPolicyVersions
              - iam:DeletePolicy
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:policy/vpc-flow-log-to-cloudwatch-*
            Effect: Allow
          - Action:
              - ec2:CreateVpc
              - ec2:ModifyVpcAttribute
              - ec2:DescribeVpcAttribute
              - ec2:DeleteVpc
            Resource: !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc/*
            Effect: Allow
          - Action:
              - ec2:CreateSubnet
              - ec2:DeleteSubnet
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:subnet/*
            Effect: Allow
          - Action:
              - ec2:CreateRouteTable
              - ec2:DeleteRouteTable
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:route-table/*
            Effect: Allow
          - Action:
              - ec2:CreateTags
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:subnet/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:internet-gateway/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:route-table/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:security-group/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:elastic-ip/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:natgateway/*
            Effect: Allow
          - Action:
              - ec2:CreateRouteTable
              - ec2:CreateRoute
              - ec2:DeleteRoute
              - ec2:DeleteRouteTable
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:route-table/*
            Effect: Allow
          - Action:
              - ec2:CreateInternetGateway
              - ec2:DeleteInternetGateway
            Resource: !Sub arn:aws:ec2:*:${AWS::AccountId}:internet-gateway/*
            Effect: Allow
          - Action:
              - ec2:AttachInternetGateway
              - ec2:DetachInternetGateway
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:internet-gateway/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc/*
            Effect: Allow
          - Action:
              - logs:CreateLogGroup
              - logs:ListTagsLogGroup
              - logs:DeleteLogGroup
            Resource: !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/vpc-flow-log/*
            Effect: Allow
          - Action:
              - ec2:RevokeSecurityGroupIngress
              - ec2:RevokeSecurityGroupEgress
            Resource: !Sub arn:aws:ec2:*:${AWS::AccountId}:security-group/*
            Effect: Allow
          - Action:
              - ec2:AssociateRouteTable
              - ec2:DisassociateRouteTable
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:route-table/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:subnet/*
            Effect: Allow
          - Action:
              - ec2:AllocateAddress
              - ec2:ReleaseAddress
              - ec2:DisassociateAddress
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:elastic-ip/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:*/*
            Effect: Allow
          - Action:
              - ec2:CreateFlowLogs
              - ec2:DeleteFlowLogs
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc-flow-log/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc/*
            Effect: Allow
          - Action:
              - ec2:CreateNatGateway
              - ec2:DeleteNatGateway
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:natgateway/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:elastic-ip/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:subnet/subnet-*
            Effect: Allow

  Route53Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Route53Policy
      Roles:
        - !Ref GitHubActionsOIDCProviderRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - route53:CreateHostedZone
              - route53:DeleteHostedZone
            Resource: '*'
          - Effect: Allow
            Action:
              - route53:GetChange
            Resource: arn:aws:route53:::change/*
          - Effect: Allow
            Action:
              - route53:GetHostedZone
              - route53:ListTagsForResource
              - route53:ChangeTagsForResource
              - route53:ListResourceRecordSets
            Resource: arn:aws:route53:::hostedzone/*

  EKSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EKSPolicy
      Roles:
        - !Ref GitHubActionsOIDCProviderRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:GetCallerIdentity
              - ec2:DescribeImages
              - ec2:DescribeTags
              - ec2:DescribeSecurityGroups
              - logs:DescribeLogGroups
              - kms:CreateKey
              - eks:CreateCluster
              - kms:ListAliases
              - eks:DescribeAddonVersions
              - ec2:DescribeSecurityGroupRules
              - eks:DeleteAddon
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeLoadBalancerAttributes
              - elasticloadbalancing:DescribeTags
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:CreateOpenIDConnectProvider
              - iam:GetOpenIDConnectProvider
              - iam:DeleteOpenIDConnectProvider
              - iam:TagOpenIDConnectProvider
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.*.amazonaws.com/id/*
          - Effect: Allow
            Action:
              - ec2:CreateSecurityGroup
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:security-group/*
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:vpc/*
          - Effect: Allow
            Action:
              - iam:CreatePolicy
              - iam:GetPolicy
              - iam:GetPolicyVersion
              - iam:ListPolicyVersions
              - iam:DeletePolicy
              - iam:TagPolicy
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:policy/*
          - Effect: Allow
            Action:
              - logs:DeleteLogGroup
            Resource: !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/eks/*/cluster:log-stream
          - Effect: Allow
            Action:
              - eks:DeleteNodegroup
            Resource: !Sub arn:aws:eks:*:${AWS::AccountId}:nodegroup/*
          - Effect: Allow
            Action:
              - logs:ListTagsLogGroup
              - logs:DeleteLogGroup
              - logs:CreateLogGroup
              - logs:TagResource
              - logs:PutRetentionPolicy
            Resource:
              - !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/eks/*/cluster
              - !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/eks/*/cluster:log-stream:*
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:PutRolePolicy
              - iam:GetRole
              - iam:ListRolePolicies
              - iam:GetRolePolicy
              - iam:ListAttachedRolePolicies
              - iam:AttachRolePolicy
              - iam:PassRole
              - iam:DetachRolePolicy
              - iam:ListInstanceProfilesForRole
              - iam:DeleteRolePolicy
              - iam:DeleteRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/*
          - Effect: Allow
            Action:
              - ec2:RevokeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:AuthorizeSecurityGroupEgress
            Resource: !Sub arn:aws:ec2:*:${AWS::AccountId}:security-group/*
          - Effect: Allow
            Action:
              - kms:EnableKeyRotation
              - kms:GetKeyRotationStatus
              - kms:GetKeyPolicy
              - kms:ListResourceTags
              - kms:DescribeKey
              - kms:ScheduleKeyDeletion
              - kms:TagResource
            Resource: !Sub arn:aws:kms:*:${AWS::AccountId}:key/*
          - Effect: Allow
            Action:
              - kms:CreateAlias
              - kms:DeleteAlias
            Resource:
              - !Sub arn:aws:kms:*:${AWS::AccountId}:alias/eks/*
              - !Sub arn:aws:kms:*:${AWS::AccountId}:key/*
          - Effect: Allow
            Action:
              - eks:DescribeCluster
              - eks:CreateNodegroup
              - eks:CreateAddon
              - eks:DeleteCluster
              - eks:TagResource
              - eks:CreateAccessEntry
              - eks:DeleteAccessEntry
            Resource: !Sub arn:aws:eks:*:${AWS::AccountId}:cluster/*
          - Effect: Allow
            Action:
              - eks:DescribeNodegroup
              - iam:DeleteRole
            Resource: !Sub arn:aws:eks:*:${AWS::AccountId}:nodegroup/*/*/*
          - Effect: Allow
            Action:
              - eks:DescribeAddon
            Resource:
              - !Sub arn:aws:eks:*:${AWS::AccountId}:addon/*/aws-ebs-csi-driver/*
              - !Sub arn:aws:eks:*:${AWS::AccountId}:addon/*/coredns/*
              - !Sub arn:aws:eks:*:${AWS::AccountId}:addon/*/kube-proxy/*
              - !Sub arn:aws:eks:*:${AWS::AccountId}:addon/*/vpc-cni/*
          - Effect: Allow
            Action:
              - ec2:DeleteTags
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:subnet/*
          - Effect: Allow
            Action:
              - ec2:DeleteSecurityGroup
            Resource:
              - !Sub arn:aws:ec2:*:${AWS::AccountId}:security-group/*
          - Effect: Allow
            Action:
              - eks:DescribeAccessEntry
              - eks:DeleteAccessEntry
              - eks:AssociateAccessPolicy
              - eks:DisassociateAccessPolicy
              - eks:ListAssociatedAccessPolicies
            Resource:
              - !Sub arn:aws:eks:*:${AWS::AccountId}:access-entry/*/role/${AWS::AccountId}/${GitHubActionsRole}/*

  GitHubActionsOIDCProviderRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      MaxSessionDuration: 3600
      RoleName: !Sub ${GitHubActionsRole}
      Description: OIDC Provider role for GitHub Actions.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/*:ref:refs/heads/*
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider

  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 1b511abead59c6ce207077c0bf0e0043b1382612
      Url: https://token.actions.githubusercontent.com
      Tags: []

Outputs:
  GitHubActionsOIDCProviderRole:
    Description: ARN of GitHubActions IAM Role.
    Value: !GetAtt GitHubActionsOIDCProviderRole.Arn

