AWSTemplateFormatVersion: "2010-09-09"

Description: Cloud Formation template to create S3 Bucket for Terraform state

Parameters:
  StateBucketName:
    Description: Name of S3 bucket for terraform state.
    Type: String

  StateLockTableName:
    Description: Name of Dynamo DB Table  for terraform state locking.
    Type: String

Resources:

  # S3 Bucket for Terraform State
  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StateBucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 365
            Prefix: terraform-state/

  StateLockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref StateLockTableName
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      BillingMode: PROVISIONED

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket for Terraform state
    Value: !Ref StateBucket

  DynamoDBTableName:
    Description: The name of the DynamoDB table for Terraform state locking
    Value: !Ref StateLockTable

