AWSTemplateFormatVersion: "2010-09-09"
Description: Cloud Formation template to configure Terraform Cloud Authentication. OIDC provider, IAM role that can be supplied to TF Cloud to authenticate.
Parameters:
  AWSRegion:
    Type: String
    Description: AWS Region.
  TFCloudOrg:
    Type: String
    Description: Terraform Cloud Organization name.
  TFCloudProject:
    Type: String
    Description: Terraform Cloud Project name.
Resources:
  PublicECRPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: ECRPublicPolicy
      Roles:
        - !Ref TerraformCloudOIDCProviderRole
      PolicyDocument: !Rain::Include ecr-policy.json
  TerraformStatePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: TerraformStatePolicy
      Roles:
        - !Ref TerraformCloudOIDCProviderRole
      PolicyDocument: !Rain::Include terraform-state-policy.json
  TerraformCloudOIDCProviderRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      MaxSessionDuration: 3600
      RoleName: "TerraformCloudOIDCProviderRole"
      Description: "OIDC Provider role for Terraform Cloud."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Condition:
              StringEquals:
                app.terraform.io:aud: "aws.workload.identity"
              StringLike:
                app.terraform.io:sub: !Sub "organization:${TFCloudOrg}:project:${TFCloudProject}:workspace:*:run_phase:*"
            Action: "sts:AssumeRoleWithWebIdentity"
            Effect: "Allow"
            Principal:
              Federated: !Ref TerraformCloudOIDCProvider
  TerraformCloudOIDCProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      ClientIdList:
        - "aws.workload.identity"
      ThumbprintList:
        - "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
      Url: "https://app.terraform.io"
      Tags: []


Outputs:
  TerraformCloudOIDCProviderRole:
    Description: ARN of Terraform Cloud IAM Role.
    Value: !GetAtt TerraformCloudOIDCProviderRole.Arn

